## 03 测试我们的算法

In [7]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()
iris.DS

AttributeError: DS

In [8]:
X = iris.data

In [9]:
y = iris.target

In [10]:
X.shape

(150, 4)

In [11]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 57, 144,  84,  27, 142, 145,  31,  65,   7,  71, 128,  99, 123,
        13,  55,  32,  78,  73,  96,  66, 127,  45, 101, 113, 147,  18,
        91,  82,  72,  25, 103,   0,  42, 148, 137, 126,  93, 111,  51,
        50,  20,  16, 121, 112,  77,  44,  95,  68,  79, 106,  62, 133,
       109, 116,  97,   8,  92,   6,  21,  35,  28,  14,  22, 105,  17,
       132,  88,  40, 118, 135, 117,  74,   9,  26, 134,  34,  63, 108,
        67, 149,  49, 146,  11, 130,  81, 143, 141,  58,  69,  19, 120,
        30,  70,  33,  24, 125, 102,  47,  39,  46, 136,  15,  54,  41,
        75,  38,  12,  29,  64, 140,  37,  59,  98, 124, 115,  90,  23,
        87, 110,  86,  61,  56,  53,  94, 119,  60,   3, 100, 114,  83,
        48, 122,  43,   4,  89, 129,  80,  85,  52,   1, 107, 138,   5,
        10, 104, 131,   2,  36,  76, 139])

In [14]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [15]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [75]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [76]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [83]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [84]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [85]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [86]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [87]:
y_predict

array([2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [88]:
y_test

array([2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 0,
       1, 1, 2, 2, 0, 0, 1])

In [90]:
sum(y_predict == y_test)

29

In [91]:
sum(y_predict == y_test) / len(y_test)

0.96666666666666667

#### sklearn中的train_test_split

In [92]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split>

In [93]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [94]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [95]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [21]:
z = np.array([1,2,3,4,5,6])
z_index = [3,4,5]
z[z_index]

array([4, 5, 6])