In [5]:
import numpy as np

In [5]:
np.__version__

'1.14.3'

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5] = 100

In [8]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [9]:
L[4] = 'Hello'

In [10]:
L

[0, 1, 2, 3, 'Hello', 100, 6, 7, 8, 9]

In [1]:
import array

第一个参数为参数类型，i为整型

In [2]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5] = 'Hello'

TypeError: an integer is required (got type str)

只能存储一个类型,当存储类型为int时，浮点数会自动进行位截断，机器学习的数据类型大多是浮点型

In [12]:
nparr = np.array([i for i in range(10)])

nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nparr[5] = 'Hello'

ValueError: invalid literal for int() with base 10: 'Hello'

In [14]:
nparr[3] = 10.6
nparr

array([ 0,  1,  2, 10,  4,  5,  6,  7,  8,  9])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10).dtype

dtype('float64')

In [29]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.zeros(shape = (3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.full(shape=(3, 5) ,fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [38]:
np.full(shape=10 ,fill_value=666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [43]:
[i for i in range(0, 30, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [41]:
np.arange(0, 20, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [45]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [48]:
np.random.randint(0, 10)

8

In [49]:
np.random.randint(0, 10, 5)

array([6, 9, 3, 9, 9])

In [50]:
np.random.randint(0, 10, size=5)

array([7, 6, 9, 5, 2])

In [51]:
np.random.randint(0, 10, size=(3,5))

array([[7, 6, 2, 4, 9],
       [2, 8, 9, 2, 4],
       [7, 5, 0, 0, 4]])

np.random.normal随机创建一个均值为0，方差为10的大小为3×5的矩阵

In [56]:
np.random.normal(0, 10, (3,5))

array([[-2.25333008, -4.93675143, -1.02844748, 16.56836644,  6.14813849],
       [11.5310176 , 22.27020843, 14.26627588, -0.37399692, 10.68277544],
       [11.34315819, 11.08615195,  1.78741198,  6.6448721 , 15.20294547]])

In [53]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap