In [1]:
import numpy as np
L = np.random.random(100)
L

array([0.68014108, 0.62600074, 0.22825585, 0.81342948, 0.1152577 ,
       0.04557014, 0.06830945, 0.20913029, 0.69438317, 0.86712479,
       0.20666167, 0.3043375 , 0.15592931, 0.43933355, 0.70873272,
       0.9747179 , 0.77127474, 0.99223118, 0.49638997, 0.4254229 ,
       0.08143291, 0.906969  , 0.30710638, 0.64198324, 0.53077772,
       0.89063883, 0.99036113, 0.27072978, 0.52574191, 0.51529426,
       0.89117942, 0.24259189, 0.24557642, 0.14631701, 0.28666641,
       0.20837381, 0.78111228, 0.01222296, 0.99063207, 0.02714313,
       0.03971932, 0.79923411, 0.89102031, 0.48631659, 0.87073018,
       0.4140114 , 0.48464242, 0.28899471, 0.54565293, 0.53747684,
       0.03817343, 0.38195068, 0.45398484, 0.86290448, 0.5046384 ,
       0.31516579, 0.12978403, 0.61017255, 0.18065028, 0.91005156,
       0.828341  , 0.04930651, 0.04092172, 0.21876876, 0.88012015,
       0.53455533, 0.66076563, 0.65183161, 0.30710419, 0.56983765,
       0.14671995, 0.88442317, 0.91571378, 0.36843654, 0.22331

In [2]:
np.sum(L)

48.4541996654922

In [3]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

175 ms ± 5.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.53 ms ± 177 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
np.min(big_array)

1.3368808698954737e-06

In [5]:
np.max(big_array)

0.99999825473455

In [6]:
big_array.min()

1.3368808698954737e-06

In [7]:
big_array.max()

0.99999825473455

In [9]:
x = np.arange(16).reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(x)

120

In [12]:
np.sum(x, axis=0)

array([24, 28, 32, 36])

In [13]:
np.sum(x, axis=1)

array([ 6, 22, 38, 54])

矩阵种的每个元素相乘

In [14]:
np.prod(x)

0

每个元素加一后的新矩阵种的每个元素相乘

In [ ]:
np.prod(x + 1)

求平均值

In [20]:
np.mean(x)

7.5

求中位数

In [21]:
np.median(x)

7.5

In [24]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [25]:
np.median(v)

2.0

In [26]:
np.percentile(big_array, q = 50)

0.5003987921043789

In [27]:
np.median(big_array)

0.5003987921043789

In [28]:
for percent in (0, 25, 50, 75, 100):
    print(np.percentile(big_array, q = percent))

1.3368808698954737e-06
0.2502854610379158
0.5003987921043789
0.7497456536832781
0.99999825473455


求方差

In [29]:
np.var(big_array)

0.0832375458997097

标准差

In [31]:
np.std(big_array)

0.28850917818972366

In [36]:
x = np.random.normal(0, 1, size=1000000)

In [37]:
np.mean(x)

0.00015934359881007834

In [42]:
np.std(x)

1.000767920100922

索引

In [44]:
np.min(x)

-5.124436208417353

In [45]:
np.argmin(x)

570979

In [46]:
x[570979]

-5.124436208417353

In [47]:
np.argmax(x)

310215

In [49]:
x[310215]

5.742173379169537

In [48]:
np.max(x)

5.742173379169537

### 排序和使用索引

In [67]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.random.shuffle(x)
x

array([13, 11,  4,  2,  0,  7,  6,  3,  1, 15,  5,  9, 10, 12, 14,  8])

In [54]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
x

array([13, 11,  4,  2,  0,  7,  6,  3,  1, 15,  5,  9, 10, 12, 14,  8])

In [56]:
x.sort()

In [57]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
X = np.random.randint(10, size=(4,4))
X

array([[0, 2, 8, 3],
       [8, 0, 9, 9],
       [0, 2, 9, 1],
       [5, 5, 2, 7]])

In [63]:
np.sort(X)

array([[0, 2, 3, 8],
       [0, 8, 9, 9],
       [0, 1, 2, 9],
       [2, 5, 5, 7]])

In [64]:
np.sort(X, axis=1)

array([[0, 2, 3, 8],
       [0, 8, 9, 9],
       [0, 1, 2, 9],
       [2, 5, 5, 7]])

In [65]:
np.sort(X, axis=0)

array([[0, 0, 2, 1],
       [0, 2, 8, 3],
       [5, 2, 9, 7],
       [8, 5, 9, 9]])

In [68]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
np.random.shuffle(x)
x

array([ 5,  9,  0,  8, 12,  4,  6,  1, 11,  3, 14,  2,  7, 15, 10, 13])

排序后，第一个元素的意思是原数组中最小的元素的下标为2，以此类推

In [71]:
np.argsort(x)

array([ 2,  7, 11,  9,  5,  0,  6, 12,  3,  1, 14,  8,  4, 15, 10, 13],
      dtype=int64)

标定点，快速排序中的思想，标定点左侧比标定点的数小，右侧数大

In [72]:
np.partition(x, 3)

array([ 2,  0,  1,  3,  4,  5,  6,  9, 11, 12, 14,  8,  7, 15, 10, 13])

In [73]:
np.argpartition(x, 3)

array([11,  2,  7,  9,  5,  0,  6,  1,  8,  4, 10,  3, 12, 13, 14, 15],
      dtype=int64)

In [74]:
X

array([[0, 2, 8, 3],
       [8, 0, 9, 9],
       [0, 2, 9, 1],
       [5, 5, 2, 7]])

In [75]:
np.argsort(X)

array([[0, 1, 3, 2],
       [1, 0, 2, 3],
       [0, 3, 1, 2],
       [2, 0, 1, 3]], dtype=int64)

In [76]:
np.argsort(X, axis=1)

array([[0, 1, 3, 2],
       [1, 0, 2, 3],
       [0, 3, 1, 2],
       [2, 0, 1, 3]], dtype=int64)

In [77]:
np.argpartition(X, 2, axis=1)

array([[0, 1, 3, 2],
       [1, 0, 2, 3],
       [0, 3, 1, 2],
       [2, 1, 0, 3]], dtype=int64)