In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [8]:
s2 = Series([4,5], index=['A','B'])

In [9]:
s1

X    1
Y    2
Z    3
dtype: int64

In [10]:
s2

A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [28]:
pd.concat([s1,s2],axis = 1)

G:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [17]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [18]:
df1

X         Y         Z
0  0.460390  0.082338  1.523411
1 -0.176652  0.344420 -0.424224
2 -0.997192  1.006922  1.406133
3  0.182727  0.193170  1.339316

In [19]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [20]:
df2

X         Y         A
0 -0.840316  0.534907 -1.077101
1 -3.248113  0.578814 -2.240045
2 -0.305896 -1.152659  0.130183

In [22]:
pd.concat([df1,df2],sort=True)

A         X         Y         Z
0       NaN  0.460390  0.082338  1.523411
1       NaN -0.176652  0.344420 -0.424224
2       NaN -0.997192  1.006922  1.406133
3       NaN  0.182727  0.193170  1.339316
0 -1.077101 -0.840316  0.534907       NaN
1 -2.240045 -3.248113  0.578814       NaN
2  0.130183 -0.305896 -1.152659       NaN

In [33]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

In [29]:
s1 = Series([2, np.nan, 4, np.nan], index=['A','B','C','D'])

In [30]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [31]:
s2 = Series([1,2,3,4], index=['A','B','C','D'])

In [32]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [33]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [34]:
df1 = DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})

In [40]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [35]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})

In [42]:
df2

A     Z
0  1   NaN
1  2  10.0
2  3   NaN
3  4  12.0

In [36]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0